### ISSUE TITLE
Configurar Prettier

### ISSUE THREAD

**Issue by rodrigosanntoos** [besafe-app/besafe-backend#20]
Prezado,

O projeto não está utilizando o Prettier, favor configurar e rodar o lint em todos os arquivos, seria interessante tbm configurar o pre-commit para verificar o lint.

-------

Confere seu Prettier, `=await` isso aqui não deveria estar junto.

_Originally posted by @rodrigosanntoos in https://github.com/besafe-app/besafe-backend/pull/19_

**Comment by nelsonsinis** [comment]
Already configured prettier, eslint and pre-commit on the project.
